server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

spring:
  rabbitmq:
    host: 10.10.53.127
    port: 5672
    username: pica8
    password: pica8

management:
  security:
    enabled: false

